### ISSUE TITLE
Not sure how serious this error is but I haven't been able to get the web-ui up and running.

### ISSUE THREAD

**Issue by swankwc** [seia-soto/stable-diffusion-webui-m1#4] opened 2022-11-04 06:13 UTC
The only command i entered to get those results is.

Install prerequisites: ./webui.sh -i

<details>
<summary>Details</summary>

 ERROR: Command errored out with exit status 1:
     command: /Users/wesley/Documents/stable-diffusion-webui/stable-diffusion-project/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e/setup.py'"'"'; __file__='"'"'/private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-record-ribhx2ah/install-record.txt --single-version-externally-managed --compile --install-headers /Users/wesley/Documents/stable-diffusion-webui/stable-diffusion-project/include/site/python3.10/onnx
         cwd: /private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e/
    Complete output (67 lines):
    fatal: not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    Using cmake args: ['/opt/homebrew/bin/cmake', '-DPYTHON_INCLUDE_DIR=/Users/wesley/.pyenv/versions/3.10.0/include/python3.10', '-DPYTHON_EXECUTABLE=/Users/wesley/Documents/stable-diffusion-webui/stable-diffusion-project/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-darwin.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e']
    -- The C compiler identification is AppleClang 14.0.0.14000029
    -- The CXX compiler identification is AppleClang 14.0.0.14000029
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /Users/wesley/Documents/stable-diffusion-webui/stable-diffusion-project/bin/python3 (found version "3.10")
    -- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES) (found version "3.10.0")
    Generated: /private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e/.setuptools-cmake-build/onnx/onnx-ml.proto
    CMake Error at CMakeLists.txt:299 (message):
      Protobuf compiler not found
    Call Stack (most recent call first):
      CMakeLists.txt:330 (relative_protobuf_generate_cpp)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e/setup.py", line 332, in <module>
        setuptools.setup(
      File "/Users/wesley/Documents/stable-diffusion-webui/stable-diffusion-project/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/wesley/Documents/stable-diffusion-webui/stable-diffusion-project/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/command/install.py", line 568, in run
        self.run_command('build')
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e/setup.py", line 223, in run
        self.run_command("cmake_build")
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e/setup.py", line 209, in run
        subprocess.check_call(cmake_args)
      File "/Users/wesley/.pyenv/versions/3.10.0/lib/python3.10/subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/opt/homebrew/bin/cmake', '-DPYTHON_INCLUDE_DIR=/Users/wesley/.pyenv/versions/3.10.0/include/python3.10', '-DPYTHON_EXECUTABLE=/Users/wesley/Documents/stable-diffusion-webui/stable-diffusion-project/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-darwin.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/wesley/Documents/stable-diffusion-webui/stable-diffusion-project/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e/setup.py'"'"'; __file__='"'"'/private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-install-5_lx_099/onnx_47bd8bac196c48ebb6ef102db45a046e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_c/wd0r0w017lx_84wcssfhc4_80000gn/T/pip-record-ribhx2ah/install-record.txt --single-version-externally-managed --compile --install-headers /Users/wesley/Documents/stable-diffusion-webui/stable-diffusion-project/include/site/python3.10/onnx Check the logs for full command output.

</details>

**Comment by seia-soto** [comment] 2022-11-04 06:37
Please, post the command you used to generate that error instead of just throwing it. Also, your system setup can affect the situation at all case. I don't recognize the error as I am not a Python developer.

**Comment by seia-soto** [comment] 2022-11-04 06:44
Couldn't reproduce the error via default commands.

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/30369714/199908800-b5403437-2887-4c17-8ab7-8a7064f1f7b5.png">

**Comment by swankwc** [comment] 2022-11-04 09:21
> Please, post the command you used to generate that error instead of just throwing it. Also, your system setup can affect the situation at all case. I don't recognize the error as I am not a Python developer.

Install prerequisites: ./webui.sh -i
That is what produced the error above, 
I'll have to look into it further in the morning.

**Comment by seia-soto** [comment] 2022-11-04 10:02
Sure, please retry after you clean up your environment.

**Comment by seia-soto** [comment] 2022-11-09 10:18
I'm closing this shortly to reduce confusion as the upstream project is growing fast. Please, comment to this issue again to be re-opened.

**Closed as completed by seia-soto** 2022-11-09 10:18 UTC
